# docker image
image: forum/metdisease

###########################################################
# variables
variables:
  # docker
  DOCKER_IMAGE: "forum/metdisease"
  # SSH / SCP
  SSH_OPTS: " -q -t "
  SSH_USER: "gitlab-bot"
  SSH_HOST: "endpoint-metabolomics.ara.inrae.fr"
  SSH_PATH: "/forum/metdiseasedatabase"
  # fetch data
  # cache
  CACHE_BASH: "/tmp/gitlab-ci-cache"
  CACHE_DOCKER: "/root/.cache-ci"

###########################################################
# cache 
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - docker_resources/
    - app/data/
    
###########################################################
# stages
stages:
  - init
  - deploy

###########################################################
# jobs

update git repo:
  stage: init
  image: pfem/ssh-utils
  tags:
    - docker
  #only:
    #refs:
      #- master
  before_script:
    - echo "==================================";
    - echo "[info] init SSH key";
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  script:
    - echo "==================================";
    - echo "[info] update git repository on $SSH_HOST ";
    - ssh $SSH_OPTS $SSH_USER@$SSH_HOST "/home/gitlab-bot/update-metdiseasedatabase-sh"
  after_script:
    - echo "==================================";

# build artifact for dev. branches
relaunch scripts:
  stage: deploy
  image: pfem/ssh-utils
  tags:
    - docker
  #only:
    #refs:
      #- master
  before_script:
    - echo "==================================";
    - echo "[info] init SSH key";
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  script:
    - echo "==================================";
    - echo "[info] run w.sh on remote server ";
    - ssh $SSH_OPTS $SSH_USER@$SSH_HOST " $SSH_PATH/w.sh ";
