# docker image
image: forum/metdisease

###########################################################
# variables
variables:
  # docker
  DOCKER_IMAGE: "forum/metdisease"
  # SSH / SCP
  SSH_OPTS: " -q -t "
  SSH_USER: "gitlab-bot"
  SSH_HOST: "147.99.132.187"
  # fetch data
  WGET_URL: "https://pfem.clermont.inra.fr/pydio/public/7af464"
  WGET_LOGIN: "--user none --password $PYDIO_PASSWD"
  # cache
  CACHE_BASH: "/tmp/gitlab-ci-cache"
  CACHE_DOCKER: "/root/.cache-ci"

###########################################################
# cache 
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - docker_resources/
    - app/data/
    
###########################################################
# stages
stages:
  - get_resources
  - docker_env
  - test

###########################################################
# jobs

# job to fetch resources from pydio
get resources:
  stage: get_resources
  tags:
    - docker
  image: cirrusci/wget
  before_script:
    - echo "==================================";
    - echo "[info] load cache ";
    - test -d $CACHE_DOCKER || mkdir -p $CACHE_DOCKER
    - test -f $CACHE_DOCKER/HumanGEM.ttl && cp -r $CACHE_DOCKER/HumanGEM.ttl docker_resources/
    - test -f $CACHE_DOCKER/metanetx.ttl && cp -r $CACHE_DOCKER/metanetx.ttl docker_resources/
    - test -f $CACHE_DOCKER/vocabulary.zip && cp -r $CACHE_DOCKER/vocabulary.zip docker_resources/
  script:
    - echo "==================================";
    - echo "[info] get resources from Pydio";
    - test -f docker_resources/HumanGEM.ttl || wget $WGET_LOGIN $WGET_URL/dl/HumanGEM.ttl -P docker_resources/
    - test -f docker_resources/metanetx.ttl || wget $WGET_LOGIN $WGET_URL/dl/metanetx.ttl -P docker_resources/
    - test -f docker_resources/vocabulary.zip || wget -O docker_resources/vocabulary.zip $WGET_LOGIN $WGET_URL/dl/vocabulary
  after_script:
    - echo "==================================";
    - echo "[info] save cache ";
    - cp -r docker_resources/HumanGEM.ttl $CACHE_DOCKER/
    - cp -r docker_resources/metanetx.ttl $CACHE_DOCKER/
    - cp -r docker_resources/vocabulary.zip $CACHE_DOCKER/

# job to build the docker env.
docker env:
  stage: docker_env
  tags:
    - bash
  before_script:
    - echo "==================================";
    - echo "[info] load cache ";
    - test -d $CACHE_BASH || mkdir -p $CACHE_BASH
    - cp -r $CACHE_BASH/HumanGEM.ttl docker_resources/
    - cp -r $CACHE_BASH/metanetx.ttl docker_resources/
    - cp -r $CACHE_BASH/vocabulary.zip docker_resources/
    - echo "[info] unzip files ";
    - rm -rf docker_resources/vocabulary/*
    - unzip docker_resources/vocabulary.zip -d docker_resources/
    # - mv docker_resources/vocabulary/* docker_resources/
    - ls -al docker_resources/vocabulary/
  script:
    - echo "==================================";
    - echo "[info] run 'docker build image' ";
    - docker build -t $DOCKER_IMAGE .

# job to run tests
test:
  stage: test
  tags:
    - docker
  before_script:
    - echo "==================================";
    - echo "[info] check TTF file symlink (or create it)";
    - test -d $CI_PROJECT_DIR/data/HumanGEM || mkdir -p $CI_PROJECT_DIR/data/HumanGEM
    - test -d $CI_PROJECT_DIR/data/MetaNetX || mkdir -p $CI_PROJECT_DIR/data/MetaNetX
    - test -f $CI_PROJECT_DIR/data/HumanGEM/HumanGEM.ttl || ln -s $CI_PROJECT_DIR/docker_resources/HumanGEM.ttl $CI_PROJECT_DIR/data/HumanGEM/HumanGEM.ttl
    - test -f $CI_PROJECT_DIR/data/MetaNetX/metanetx.ttl || ln -s $CI_PROJECT_DIR/docker_resources/metanetx.ttl $CI_PROJECT_DIR/data/MetaNetX/metanetx.ttl
  script:
    - echo "==================================";
    - echo "[info] test 'docker image' ";
    - python3 $CI_PROJECT_DIR/app/build_RDF_store/Elink_ressource_creator.py
    - python3 $CI_PROJECT_DIR/app/build_RDF_store/download_functions.py
    - python3 $CI_PROJECT_DIR/app/build_RDF_store/parse_pubchem_RDF.py
    - python3 $CI_PROJECT_DIR/app/metab2mesh/processing_functions.py
    - python3 $CI_PROJECT_DIR/app/metab2mesh/SPARQL/cid_mesh.py
    - python3 $CI_PROJECT_DIR/app/SBML_upgrade/Id_mapping.py
    - python3 $CI_PROJECT_DIR/app/SBML_upgrade/processing_functions.py
