version: '3'
services:
    virtuoso:
         image: tenforce/virtuoso                    
         environment:
              VIRT_Parameters_NumberOfBuffers: 2720000   # See virtuoso/README.md to adapt value of this line
              VIRT_Parameters_MaxDirtyBuffers: 2000000    # See virtuoso/README.md to adapt value of this line
              VIRT_Parameters_MaxCheckpointRemap: 680000
              VIRT_Parameters_TN_MAX_memory: 2000000000
              VIRT_SPARQL_ResultSetMaxRows: 10000000000
              VIRT_SPARQL_MaxDataSourceSize: 10000000000
              VIRT_Flags_TN_MAX_memory: 2000000000
              VIRT_Parameters_StopCompilerWhenXOverRunTime: 1
              VIRT_SPARQL_MaxQueryCostEstimationTime: 0       # query time estimation
              VIRT_SPARQL_MaxQueryExecutionTime: 50000          # 5 min
              VIRT_Parameters_MaxMemPoolSize: 200000000
              VIRT_HTTPServer_EnableRequestTrap: 0
              VIRT_Parameters_ThreadCleanupInterval: 1
              VIRT_Parameters_ResourcesCleanupInterval: 1
              VIRT_Parameters_AsyncQueueMaxThreads: 1
              VIRT_Parameters_ThreadsPerQuery: 1
              VIRT_Parameters_AdjustVectorSize: 1
              VIRT_Parameters_MaxQueryMem: 2G
              VIRT_Database_LockFile: virtuoso.lck
              DBA_PASSWORD: "FORUM-Met-Disease-DB"
              SPARQL_UPDATE: "false"
              DEFAULT_GRAPH: "http://database/ressources/"
         volumes:
            - /home/mxdelmas/Documents/Thèse/building_database/FORUM/metdiseasedatabase/docker-virtuoso/share:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/dumps
            - ./data/virtuoso:/data
         ports:
            - 9980:8890

